# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestNewsApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestNewsApi
  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '5.0.0'
  pod 'RxCocoa', '5.0.0'
  pod 'Swinject', '2.0.0'

  target 'TestNewsApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestNewsApiUITests' do
    # Pods for testing
  end

end
